### ISSUE TITLE
issue_buried_objects

### ISSUE THREAD

**Issue by Hanziscool** [learningLogisticsLab/robosuite#2]
#### These objects are buried down in the table.

1. o0027 plate 
<img width="1432" alt="issue3_plate" src="https://user-images.githubusercontent.com/27131476/127601546-874e1be4-a4ee-44f5-b201-a17fa5c054ba.png">Bottom part of the plate got buried.

2. o0035 padlock 
<img width="1432" alt="issue5_lock" src="https://user-images.githubusercontent.com/27131476/127620311-71a5b92e-559f-458f-bc7f-63d87039c5bc.png">Circular part of the lock (lock head) got buried.

3. o0054 dice
<img width="1432" alt="issue8_dice" src="https://user-images.githubusercontent.com/27131476/127620322-cd004f31-b3bd-447d-afa4-9f1d100be4ee.png">Dice almost got completely buried.

**Need to look deeper at `z_offset` in `_get_placement_initializer` function in `picking.py`**

**Comment by rojas70** [comment]
completed by changing some of the mujoco properties of the objects. lost which commit we did this on.
