### ISSUE TITLE
falling_objects_issue

### ISSUE THREAD

**Issue by Hanziscool** [learningLogisticsLab/robosuite#5]
Checking for Objects that fall

1. We need to develop a logic such that:
2. Detect if the object falls (i.e. if its height is less than the bin height)
3. If so, remove the object from lists where we track objects. like the sorted_object_list
<img width="1439" alt="Screenshot 2021-08-20 at 10 44 52 AM" src="https://user-images.githubusercontent.com/27131476/130171184-a844e5e9-6b08-4431-86a0-1696f8c59424.png">

**Comment by rojas70** [comment]
completed.
